server:
  port: 8083
dubbo:
  application:
    name: item_web
  registry:
    address: zookeeper://192.168.227.188:2181
  consumer:
    check: false
    timeout: 10000
spring:
  rabbitmq:
    host: 192.168.227.188
    virtual-host: /