server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      #限制上传文件的大小
      max-file-size: 10MB
      max-request-size: 10MB
dubbo:
  application:
    name: back_web
  registry:
    address: zookeeper://192.168.227.188:2181
  consumer:
    check: false
    timeout: 10000
    retries: 0
upload:
  path: C:/worker/img/
fdfs:
  so-timeout: 10000
  connect-timeout: 10000
  tracker-list:
    - 192.168.227.188:22122
  thumb-image:
    width: 100
    height: 100
  pool:
    jmx-enabled: false