spring:
  datasource:
    url: jdbc:mysql:///shop1903
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: goods_service
  registry:
    address: zookeeper://192.168.227.188:2181
  protocol:
    name: dubbo
    port: -1