server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///stu_db1
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  datasource2:
    url: jdbc:mysql:///stu_db2
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml